# Generated by Django 5.1.2 on 2024-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclaim_vendor_id', models.CharField(max_length=50)),
                ('ap_vendor_id', models.CharField(max_length=50)),
                ('ap_vendor_number', models.CharField(max_length=50)),
                ('ap_vendor_name', models.CharField(max_length=255)),
                ('ap_vendor_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('inactive_date', models.DateField(blank=True, null=True)),
                ('vendor_contact', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('customer_vendor', models.CharField(max_length=255)),
                ('swell_flag', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('client', models.CharField(max_length=100)),
                ('reclaim_inactive_date', models.DateField(blank=True, null=True)),
                ('auth_for_debt', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('apply_max_vend_cost', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('auth_reason', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_scan', models.DateField(blank=True, null=True)),
                ('scans_per_week', models.PositiveIntegerField(default=0)),
                ('dollars_per_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('on_hold', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('vendor_type_def', models.CharField(max_length=100)),
            ],
        ),
    ]
